package cli

import (
	"strings"

	"github.com/spf13/cobra"
)

// CommandNode is one visible Cobra command paired with the catalog path used by
// tests and docs. Path is CommandPath() minus the leading "chab ".
type CommandNode struct {
	Path    string
	Command *cobra.Command
}

// VisibleCommands walks the user-visible commands below root in Cobra's sorted
// order. It always includes the root-level default help command and always
// skips hidden __complete* internals; root itself is not returned. When
// descendCompletion is false the walk stops at the completion command; when it
// is true generated completion shell children are included.
func VisibleCommands(root *cobra.Command, descendCompletion bool) []CommandNode {
	var commands []CommandNode

	var walk func(parent *cobra.Command)
	walk = func(parent *cobra.Command) {
		for _, child := range parent.Commands() {
			includeDefaultHelp := parent == root && child.Name() == "help"
			if !child.IsAvailableCommand() && !includeDefaultHelp {
				continue
			}

			path := strings.TrimPrefix(child.CommandPath(), "chab ")
			if path == "" || strings.HasPrefix(path, "__complete") {
				continue
			}
			commands = append(commands, CommandNode{Path: path, Command: child})

			// Completion shell children are generated by Cobra. Catalog/docs treat
			// them as one "completion" surface, but help linting descends into
			// them so their generated help stays safe.
			if !descendCompletion && path == "completion" {
				continue
			}
			walk(child)
		}
	}

	walk(root)
	return commands
}
