package manualdocs

import (
	"errors"
	"os"
	"path/filepath"
	"sort"
)

// CheckResult groups the three ways generated manual files can drift from the
// current generator output.
type CheckResult struct {
	Missing  []string
	Stale    []string
	Orphaned []string
}

// OK reports whether the generated manual docs on disk match exactly.
func (r CheckResult) OK() bool {
	return len(r.Missing) == 0 && len(r.Stale) == 0 && len(r.Orphaned) == 0
}

// Write writes every generated file relative to baseDir, creating directories
// as needed. It intentionally does not delete orphaned files; Check reports
// those so a caller can review removals explicitly.
func Write(baseDir string, files map[string][]byte) error {
	for rel, data := range files {
		path := filepath.Join(baseDir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(path, data, 0o644); err != nil {
			return err
		}
	}
	return nil
}

// Check compares generated bytes with files on disk and also reports old
// markdown files that the generator no longer owns.
func Check(baseDir string, files map[string][]byte) (CheckResult, error) {
	var result CheckResult
	for rel, want := range files {
		path := filepath.Join(baseDir, filepath.FromSlash(rel))
		got, err := os.ReadFile(path)
		if errors.Is(err, os.ErrNotExist) {
			result.Missing = append(result.Missing, rel)
			continue
		}
		if err != nil {
			return CheckResult{}, err
		}
		if string(got) != string(want) {
			result.Stale = append(result.Stale, rel)
		}
	}

	expected := make(map[string]bool, len(files))
	for rel := range files {
		expected[rel] = true
	}
	// If manual/commands does not exist, the per-file pass above has already
	// reported every generated file as missing.
	docsDir := filepath.Join(baseDir, "manual", "commands")
	err := filepath.WalkDir(docsDir, func(path string, entry os.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if entry.IsDir() || filepath.Ext(path) != ".md" {
			return nil
		}
		rel, err := filepath.Rel(baseDir, path)
		if err != nil {
			return err
		}
		rel = filepath.ToSlash(rel)
		if !expected[rel] {
			result.Orphaned = append(result.Orphaned, rel)
		}
		return nil
	})
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return CheckResult{}, err
	}

	sort.Strings(result.Missing)
	sort.Strings(result.Stale)
	sort.Strings(result.Orphaned)
	return result, nil
}
